### ISSUE TITLE
GUI version doesn't work on Fedora 25

### ISSUE THREAD

**Issue by etem** [M1ND-B3ND3R/BoopSuite#6]
After the installation I faced several issues on Fedora :

 Boopsniff_gui threw an error message about missing modules : 

```

[root@localhost bavarian] # boopsniff_gui 
Traceback (most recent call last):
  File "/usr/local/bin/boopsniff_gui", line 17, in <module>
    import tkFileDialog
ImportError: No module named tkFileDialog
```
I had to install tkinter packaga via DNF to fix this. 
Then another error message appreared : 

```
[root@localhost bavarian] # boopsniff_gui 
Traceback (most recent call last):
  File "/usr/local/bin/boopsniff_gui", line 23, in <module>
    from tkinter import *
ImportError: No module named tkinter

```
I found that the module name is starting with capital letter on python versions <3.0.
Renaming the module at line 23 fixed this problem too. 

But now I get one more error message related to display settings : 

```
[root@localhost bavarian] # boopsniff_gui 
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/usr/local/bin/boopsniff_gui", line 679, in <module>
    start_gui(configuration)
  File "/usr/local/bin/boopsniff_gui", line 671, in start_gui
    root = Tk()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1820, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"
```

Maybe this is because Fedora uses Wayland instead of X.org server by default?

**Comment by M1ND-B3ND3R** [comment]
I took out the old dependencies and will be commiting a fix later today. 

Thanks for your interest in the project. :)

**Comment by M1ND-B3ND3R** [comment]
I just commited a fix, let me know if it fixes it. Else I will look more into the issue. The code should work on python2.7 as intended so cross the fingers.

**Comment by etem** [comment]
Looks like it fails to detect the package manager : 

```
[root@localhost BoopSuite] # ./install.py 

,_,_,_,_,_,_,_,_,_,_|____________________BOOP-INSTALLER____________________
|#|#|#|#|#|#|#|#|#|#|_____________________________________________________/
'-'-'-'-'-'-'-'-'-'-|----------------------------------------------------'
                                          M1ND-B3ND3R
    
which: no apt-get in (/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/bavarian/bin)
Traceback (most recent call last):
  File "./install.py", line 121, in <module>
    install();
  File "./install.py", line 116, in install
    Install_Packages(Package_Manager);
  File "./install.py", line 49, in Install_Packages
    subprocess.check_output([Package_Manager, "install", package, "-y"], stderr=subprocess.STDOUT);
  File "/usr/lib64/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
[root@localhost BoopSuite] # 

```
I've tried to add **dnf** to the list with package managers but it still searches for apt-get and shows the same error message.

**Comment by M1ND-B3ND3R** [comment]
What package manager are you using?

**Comment by etem** [comment]
DNF, Fedora includes it by default. 

Yum is also present but it's just a symlink to DNF.

`➜  ~ yum
Redirecting to '/usr/bin/dnf ' (see 'man yum2dnf')
`

**Comment by M1ND-B3ND3R** [comment]
Never used dnf, so I might have to install fedora and give it a try
