### ISSUE TITLE
Error installing scapy

### ISSUE THREAD

**Issue by codivist** [M1ND-B3ND3R/BoopSuite#9]
I'm running Raspian 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

when I run `pip install -r requirements.txt` the first three install fine, but scapy errors out. I tried installing it manually and it gave the same error:
```
Downloading/unpacking scapy
  Downloading scapy-2.3.3.tgz (1.4Mb): 1.4Mb downloaded
  Running setup.py egg_info for package scapy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/BoopSuite/build/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/BoopSuite/build/scapy/setup.py", line 36

    os.chmod(fname, 0755)

                       ^

SyntaxError: invalid token

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/BoopSuite/build/scapy
Storing complete log in /root/.pip/pip.log
```

I succussfully ran `sudo apt-get install python-scapy` and it installed

when I try to run any boopsniff command I just get this now:
```
Traceback (most recent call last):
  File "/usr/local/bin/boopsniff", line 12, in <module>
    import pyric.pyw as pyw
ImportError: No module named pyric.pyw
```

**Comment by codivist** [comment]
Output of my pip.log:
```
  Getting page http://pypi.python.org/simple/scapy
  URLs to search for versions for scapy (from -r requirements.txt (line 4)):
  * http://pypi.python.org/simple/scapy/
  Getting page http://pypi.python.org/simple/scapy/
  Analyzing links from page https://pypi.python.org/simple/scapy/
    Found link https://pypi.python.org/packages/4e/f7/700afef531954770c6199f073edc7f599f6cfd6b61c4f69dac99f51f967b/scapy-2.2.0-dev.zip#md5=185d5cd91ce36c449c2f02ff8cb1f2a0 (from https://pypi.python.org/simple/scapy/), version: 2.2.0-dev
    Found link https://pypi.python.org/packages/6d/72/c055abd32bcd4ee6b36ef8e9ceccc2e242dea9b6c58fdcf2e8fd005f7650/scapy-2.3.2.tar.gz#md5=b8ca06ca3b475bd01ba6cf5cdc5619af (from https://pypi.python.org/simple/scapy/), version: 2.3.2
    Found link https://pypi.python.org/packages/72/0b/5381f2a376035d06937064fb4ecfaf2c69fd94327000e13615a4f5d4cc13/scapy-2.2.0-dev.linux-x86_64.tar.gz#md5=84e62f8c244d6e68daa5f7d1de645191 (from https://pypi.python.org/simple/scapy/), version: 2.2.0-dev.linux-x86_64
    Found link https://pypi.python.org/packages/ac/14/c792a14b9f8bc4bb9c74c0594c167a2da36e31964098d9e27202142cbd7d/scapy-2.3.3.tgz#md5=65939356f08760ebef836796d3320b3b (from https://pypi.python.org/simple/scapy/), version: 2.3.3
    Found link https://pypi.python.org/packages/ee/cd/d20c1e121b09697bf4d7b1b9edde6573fc7d54eefc56860f457a7edfc0de/scapy-2.3.1.zip#md5=1527f09562d9c1bafa5e619c7782d5a0 (from https://pypi.python.org/simple/scapy/), version: 2.3.1
    Found link https://pypi.python.org/packages/f3/29/48d6ed3c95571b5ff3ee91b1c987c820e7c5265dfd2c46b566573d87c662/scapy-2.2.0-dev.tar.gz#md5=1a5115d1f33548501d01d735bd689f13 (from https://pypi.python.org/simple/scapy/), version: 2.2.0-dev
  Using version 2.3.3 (newest of versions: 2.3.3, 2.3.2, 2.3.1, 2.2.0-dev.linux-x86_64, 2.2.0-dev, 2.2.0-dev)
  Downloading from URL https://pypi.python.org/packages/ac/14/c792a14b9f8bc4bb9c74c0594c167a2da36e31964098d9e27202142cbd7d/scapy-2.3.3.tgz#md5=65939356f08760ebef836796d3320b3b (from https://pypi.python.org/simple/scapy/)
  Running setup.py egg_info for package scapy

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/home/pi/BoopSuite/build/scapy/setup.py", line 36

        os.chmod(fname, 0755)

                           ^

    SyntaxError: invalid token

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/BoopSuite/build/scapy/setup.py", line 36

    os.chmod(fname, 0755)

                       ^

SyntaxError: invalid token

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/pi/BoopSuite/build/scapy

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/pi/BoopSuite/build/scapy
```

**Comment by M1ND-B3ND3R** [comment]
try running: "pip install pyric" See if that fixes the pyric error.

**Comment by codivist** [comment]
After running that just got the following:
```Requirement already satisfied (use --upgrade to upgrade): pyric in /usr/local/lib/python3.2/dist-packages
Cleaning up...
```
I'll try a couple different things and see if I can't get it going.

**Comment by gusennan** [comment]
The issue here is that scapy is not Python 3 compatible.  Try installing using Python 2. 
 http://www.secdev.org/projects/scapy/
